README.md, lib/index.js, lib/index.test.js
BREAKING CHANGE: session is now exposed in req.session as this is the way
express-session does too
=> feat(API): expose session as req.session instead of arg to handler

lib/index.js, lib/index.test.js
**The PR is now only a fix for a typo problem.**
---------------
It's useless to add an `await` when we already return a promise.
See the eslint rule for example: https://eslint.org/docs/rules/no-return-await
(also fixed a small typo)
Edit: initially I removed both 2 `await`s but as the first one is required to check the error, I created a variable to remove the `return await`.
Tell me what do you think :)
=> fix(lib): typo in error message

README.md, lib/index.js, lib/index.test.js, package.json, yarn.lock
Example usage:
```js
export default withIronSession(handler, {
password: [
{
id: 2,
password: "another_password_at_least_32_characters_long",
},
{
id: 1,
password: "complex_password_at_least_32_characters_long",
},
],
});
```
fixes #69
=> feat(password): allow for multiple passwords (password rotation)

examples/next.js/README.md
The link in was "https://github.com/vvo/next-iron/session" when it should be "https://github.com/vvo/next-iron-session
=> docs(Readme): header link redirecting to 404 page

lib/index.js, lib/index.test.js
This commit fixes a case where previous set-cookie headers were ignored through
the request lifecycle. This is now fixed and handles both single and multiple
set-cookie header values. Since in Node.js you can do:
res.setHeader("set-cookie", "name=value"); and
res.setHeader("set-cookie", ["name=value", "name2=value2"])
fixes #112
=> fix(cookie): handle previously set-cookie headers

README.md
Instructions in README under **applySession** were incorrectly displaying an unintended example import from `next-session` instead of `next-iron-session`.
=> docs(example): Amend import example in README.md

lib/index.d.ts
I was trying out the library in a TypeScript Next.js app and I thought it was weird that Session.set didn't return the value that was passed in. I realised that it actually does after digging in a little bit, so this PR is primarily to fix that.
Additionally, I thought I'd check the other types on the Session and also found that Session.save returns the cookie header value as a string.
=> fix(TypeScript): correct typing on Session

examples/next.js/lib/session.js
=> fix: typo `environment`

README.md
The README documentation mentions that `destroy()` returns a promise. However, looking at the code, it only performs synchronous tasks. The TS types also define `destroy()` as returning `void`.
=> Fix README - destroy() returns void, not promise

examples/next.js/lib/session.js
=> docs: The API requires cookieName to be passed to withIronSession(), so including it in the ReadMe guide files.

package.json
Add `repository` key in `package.json`.
This means that the right-hand bar on https://www.npmjs.com/package/iron-session will show a link to the repository, which I personally find convenient (e.g. for accessing release notes).
=> chore(pkg): add repository key in package.json

README.md
There is a redundant closing parenthesis in the **Advanced usage** section in the project `README.md`.
=> docs: redundant closing parenthesis in `README.md`

package.json
When you search for this repository online, the first hit is its [npm](https://www.npmjs.com/package/iron-session), where no github data is shown (Repository, issues). This means you have to search again to get to the the repo's Github page.
Also added keywords for people searching on npm.
=> chore: add/fix meta data used by npm

README.md
Previously clicking on the badge would take you to the icon instead on npm
=> docs: Fix npm link in README

README.md, next/index.test.ts, next/index.ts
This adds ability to pass options built using request or response object. 
This will resolve the issues people have in https://github.com/vvo/iron-session/issues/410
@vvo mentioned making maxCookieAge or cookieName functions but that approach will require changing the signature of the underlying cookie type which is coming from another package. It is also not very flexible and will require bigger changes. 
That's why I'm going with current approach where you can pass a function which returns option object and use request or response props in it. 
I'm happy to make any changes. Let me know.
=> feat(next): Add ability to dynamically compute iron options based on req, res

next/index.test.ts, next/index.ts
I accidentally ended up reusing the options variable which is coming from the middleware so it is set and run only once which is not the intended behavior.
This fixes the behavior. 
@vvo
=> fix(next): Fix options variable reuse

examples/next.js-typescript/pages/login.tsx, examples/next.js/pages/login.js
The login endpoint returns anyhow what the user endpoint does, so disable SWR revalidation after mutate.
=> fix(examples): unnecessary fetch of user after login

README.md
this makes the module augmentation work on files like `additional.d.ts`
=> add iron session import to ts definitions

README.md
To respect the differences in client-side and server-side navigation, and to help ensure that developers do not build insecure Middleware, Middleware can no longer produce a response body. This ensures that Middleware is only used to rewrite, redirect, or modify the incoming request (e.g. setting cookies).
=> docs: correct next.js middleware example

README.md
the `getSessionData()` function assigns the session data to the `session` variable, but doesn't return anything, making the example incorrect.
=> chore: fix readme Example
